### PR TITLE
Add Sfinv support.

### PR DESCRIPTION
**Pull request by shacknetisp**
Since Sfinv is the Minetest Game inventory, it's fairly important to have compatibility with it.

### CODE REVIEW

**Comment by bell07** [comment]
Please add sfinv? to depends.txt to be sure the sfinv is loaded before sfinv. Without them it does not work for me.
apart from that good work :+1:

**Comment by shacknetisp** [comment]
Woops, fixed that now.

**Comment by shacknetisp** [comment]
There was another problem: events like sfinv tab changes would be propagated to the smartfs form. 
My latest commit fixes this by adding receive and leave functions to the sfinv page registry and disabling smartfs's builtin receiving when `inventory_handles_fields` is true in the state location.

It also corrects the `player` field of the state location to be a name, not the actual player object.

**Comment by bell07** [comment]
Tested more, the toggle buttons does not work

**Comment by bell07** [comment]
Did a PR to your fork with fix the toggle

**Comment by shacknetisp** [comment]
I added one more fix: clearing `smartfs.inv[name]` when the page is left. Otherwise when smartfs has two sfinv pages the first one opened will always display instead of the other.

**Comment by shacknetisp** [comment]
I think the other inventory plugins will have this issue too (toggle buttons + overriding), but that is for another PR.

**Comment by bell07** [comment]
Looks all fine.
Confirm the other Inventories have the same issues with dynamic elements. Tested with unified_inventory :-( But it is an other issue #50

I see the bypass the context is a bad idea. Please remove it again. This way it is possible to override sfinv internal data by misstake :-(

**Comment by bell07** [comment]
From my point of view this PR can be merged. @rubenwardy your opinion?

**Comment by rubenwardy** [comment]
Looks good to me. The commits should be squashed such that there's one for each author. Unless bell07 is happy to go without credit

**Comment by bell07** [comment]
Ok, squashed and merged


> Unless bell07 is happy to go without credit

No problem, I have enough own commits in project ;-)

**Comment by rubenwardy** [comment]
Coolio :)

**Pull request merged**
