### PR TITLE
added state:loadTemplate()

### PR DESCRIPTION
**Pull request by bell07**

### CODE REVIEW

**Comment by rubenwardy** [comment]
loadTemplate makes it sound like it's loading from a file then changing variables - maybe one of:

* addAllFromForm()
* addAll()

**Comment by bell07** [comment]
"loadTemplate" was the first idea, but I don't like it too. But addAllFromForm() is also not yet "perfect" name.
The Idea was born to be able to define "Reusable headers", same header in multiple forms:
https://github.com/bell07/minetest-smartfs/blob/master/docs/example-container.lua
```
local header_form_function = function(state)
	local label = state:label(0,0,"lbl","SmartFS formspec using nested containers")
--...
end
local main_form_function = function(state)
	state:size(10,10)
	state:loadTemplate(header_form_function)
--...
end
```
In the fact I use only the way "by function", so the  type(template) == "string"  or "table" can be removed again for me.
Maybe remove the both and rename to something like "state:fromCallbackFunction(function)"?

The second use-case is to fill Sub-Views (now called "container")
```
	tab1.container = tab_state:container(0,1,"tab1_container")
	tab1.containerstate = tab1.container:getContainerState()
	tab1.containerstate:loadTemplate(tab1_def)
```

**Comment by bell07** [comment]
Some proposals more:
```
inject()
include()
customCallback()
```
???
Or just reject the change, there is a way I see now just to use `header_form_function(state)` unstead of `state:loadTemplate(header_form_function)`. But I like to see an "official method" for this injection.

**Comment by bell07** [comment]
Yea, this PR was a classic newbie thing, a workaround for an existing functionality. Since I know about the my_function(state) way I do not use the loadTemplate() anymore. Therefore I close this PR again and will remove the function from my fork.

**Pull request closed without merging**
