### PR TITLE
Add getBackground/setBackground support for each element

### PR DESCRIPTION
**Pull request by bell07**

### CODE REVIEW

**Comment by rubenwardy** [comment]
Looks pretty sweet. One problem however is that the formspec co-ordinate system is very inconsistent between element types, so some of the backgrounds may be misplaced

**Comment by bell07** [comment]
Yea, the formspec co-ordniates :(
But it should not be a smarfts problem. The main idea for this change is to set backgrounds on containers. The second: why not for all elements?.
Anyway, I added "is_background" attribute to the image element to be able to set background only

**Comment by rubenwardy** [comment]
I suggest adding state:background which is state:image but with is_background=true and not a parameter

**Comment by bell07** [comment]
Done. like field=>pwdfield

**Comment by bell07** [comment]
I changed the bool "is_background" to "imgtype" that can have more then 2 values. There is a image type item_image that will be added at the next

**Comment by bell07** [comment]
Please check the changes now. The background string is set now inside of _buildFormspec_ instead of each element. That should be more proper.
From practice: you are right, in most cases the element:setBackground() is useless because the coordinates does not match to the element. But in some cases like highlighting of buttons the method is irreplaceable. No need to define an background element for each button, and get the coordinates in sync, just set background at runtime for the button that needs to be highlighted.

**Comment by bell07** [comment]
Yes, I am ready ;)

**Pull request merged**
