### PR TITLE
Add show_inv parameter to smartfs.add_to_inventory

### LINKED ISSUE #49: Add the ability to register in inventory mods without displaying the player inventory.
In unified inventory this can be accomplished with `fsdata.draw_inventory = false` in the `get_formspec` return.
In sfinv, pass `false` after the actual formspec string to `sfinv.make_formspec`.

What is the best way to implement this?

### PR DESCRIPTION
**Pull request by shacknetisp**
This parameter tells the inventory mod whether to automatically add the player inventory to the formspec or not.

I have the parameter defaulting to `true` if not specified, to maintain backwards compatibility. Let me know if you'd rather it default to `false`.

Closes #49

### CODE REVIEW

**Comment by shacknetisp** [comment]
Rebased on master to fix conflicts.

**Comment by bell07** [comment]
Did you seen my review comment?
return ldef.add_to_inventory(form, icon, title, show_inv) should be enough because "true if nil" is by default in both inventories. There is no need for "(show_inv == nil) and true or show_inv"

**Comment by rubenwardy** [comment]
> Did you seen my review comment? return ldef.add_to_inventory(form, icon, title, show_inv) should be  enough because "true if nil" is by default in both inventories. There is no need for "(show_inv == nil) and true or show_inv"

It would be worth adding a comment warning about this if you do this. In the future, an inv mod may be added which doesn't default to this but the API should be consistent

**Comment by shacknetisp** [comment]
> Did you seen my review comment?
return ldef.add_to_inventory(form, icon, title, show_inv) should be enough because "true if nil" is by default in both inventories. There is no need for "(show_inv == nil) and true or show_inv"

Sorry, no, where was it posted?

I did choose this method for the sake of consistency, as @rubenwardy said. If there was ever an inventory mod that did not default to true or even failed on `nil` it'd break without a default.

**Pull request merged**
